'use client';

import { useEffect } from 'react';
import { X } from 'lucide-react';

interface MethodologyModalProps {
  isOpen: boolean;
  onClose: () => void;
}

export default function MethodologyModal({ isOpen, onClose }: MethodologyModalProps) {
  // ESC key handler
  useEffect(() => {
    if (!isOpen) return;
    
    const handleEscKey = (e: KeyboardEvent) => {
      if (e.key === 'Escape') {
        onClose();
      }
    };
    
    window.addEventListener('keydown', handleEscKey);
    return () => window.removeEventListener('keydown', handleEscKey);
  }, [isOpen, onClose]);

  if (!isOpen) return null;

  const handleBackdropClick = (e: React.MouseEvent) => {
    if (e.target === e.currentTarget) {
      onClose();
    }
  };

  return (
    <div 
      className="fixed inset-0 z-[100] flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm animate-in fade-in duration-300"
      onClick={handleBackdropClick}
    >
      <div 
        className="relative w-full max-w-lg bg-black/70 backdrop-blur-[16px] rounded-xl border border-white/15 shadow-2xl overflow-hidden animate-in zoom-in-95 duration-300"
        onClick={(e) => e.stopPropagation()}
      >
        {/* Header */}
        <div className="flex items-center justify-between p-6 border-b border-white/10">
          <h2 className="text-xl font-bold text-white">Scoring Methodology</h2>
          <button
            type="button"
            onClick={(e) => {
              e.preventDefault();
              e.stopPropagation();
              onClose();
            }}
            className="relative z-10 p-2 rounded-lg bg-black/30 hover:bg-black/50 border border-white/10 hover:border-[#E4FF3A]/30 transition-all duration-300 cursor-pointer"
            aria-label="Close"
          >
            <X className="w-5 h-5 text-white/70 hover:text-[#E4FF3A]" />
          </button>
        </div>

        {/* Content */}
        <div className="p-6 space-y-4 max-h-[60vh] overflow-y-auto">
          <div className="space-y-3">
            <h3 className="text-lg font-semibold text-white">How We Calculate Scores</h3>
            <p className="text-white/80 text-sm leading-relaxed">
              Our sustainability scores are generated using AI-powered analysis that evaluates brands across multiple dimensions of environmental and social responsibility.
            </p>
          </div>

          <div className="space-y-3">
            <h4 className="text-md font-semibold text-white">Score Ranges</h4>
            <ul className="space-y-2 text-sm text-white/80">
              <li className="flex items-center gap-3">
                <span className="w-16 text-green-500 font-semibold">80-100</span>
                <span>Industry leader in sustainability</span>
              </li>
              <li className="flex items-center gap-3">
                <span className="w-16 text-green-400 font-semibold">60-79</span>
                <span>Making good progress</span>
              </li>
              <li className="flex items-center gap-3">
                <span className="w-16 text-yellow-500 font-semibold">40-59</span>
                <span>Average, room for improvement</span>
              </li>
              <li className="flex items-center gap-3">
                <span className="w-16 text-orange-500 font-semibold">0-39</span>
                <span>Significant concerns</span>
              </li>
            </ul>
          </div>

          <div className="space-y-3">
            <h4 className="text-md font-semibold text-white">Evaluation Criteria</h4>
            <ul className="space-y-1.5 text-sm text-white/80 list-disc list-inside">
              <li>Carbon footprint and emissions reduction targets</li>
              <li>Supply chain transparency and ethical sourcing</li>
              <li>Waste reduction and circular economy initiatives</li>
              <li>Renewable energy adoption</li>
              <li>Third-party certifications and audits</li>
              <li>Labor practices and worker welfare</li>
              <li>Community impact and social responsibility</li>
            </ul>
          </div>

          <div className="pt-2">
            <p className="text-white/60 text-xs leading-relaxed">
              Note: Scores are generated by AI analysis and should be used as a general guide. We recommend conducting additional research for important decisions.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
